# === Antifilter Sources ===
antifilter_download=yes
antifilter_network=no

# antifilter.download lists
ip=no
ipresolve=no
ipsum=no
subnet=no
allyouneed=yes
community=no

# antifilter.network lists
nf_ip=yes
nf_ipsmart=yes
nf_ipsum=yes
nf_subnet=yes
nf_uablacklist=yes
nf_govno=yes
nf_ip6=yes
