log syslog all;
router id 10.137.10.253;

protocol device {
}

protocol direct {
    disabled;
    ipv4;
    ipv6;
}

protocol kernel {
    ipv4 {
		import none;
		export none;
    };
}

protocol kernel {
    ipv6 { export none; };
}

protocol static static_all {
    ipv4;
    include "/etc/bird/list_rsc/allyouneed.rsc";
    include "/etc/bird/list_rsc/Cloudflare.rsc";
    include "/etc/bird/list_rsc/AWS-Amazon.rsc";
    include "/etc/bird/list_rsc/Discord.rsc";
    include "/etc/bird/list_rsc/Google.rsc";
    include "/etc/bird/list_rsc/Meta.rsc";
    include "/etc/bird/list_rsc/Openh264.rsc";
    include "/etc/bird/list_rsc/Telegram.rsc";
    include "/etc/bird/list_rsc/WebNovel.rsc";
}

filter bgp_out_all {
    if proto = "static_all" then {
        bgp_community.add((64500, 100));
        accept;
    }
    reject;
}

protocol bgp MRK_CHR_GW01 {
    description "Mikrotik CHR GW01";
    neighbor 10.137.10.1 as 64501;
    hold time 240;
    local as 64500;
    passive on;
    ipv4 {
        import none;
        export filter bgp_out_all;
        next hop self;
    };
}

protocol bgp MRK_CHR_GW02 {
    description "Mikrotik CHR GW02";
    neighbor 10.137.13.1 as 64502;
    hold time 240;
    local as 64500;
    passive on;
    ipv4 {
        import none;
        export filter bgp_out_all;
        next hop self;
    };
}